export { default as AuthorListPage } from "./pages/AuthorListPage";
export { default as CreateAuthorPage } from "./pages/CreateAuthorPage";
export { default as EditAuthorPage } from "./pages/EditAuthorPage";
export { authorService } from "./services/author.service";
export { useAuthors } from "./hooks/useAuthors";
export { useAuthor } from "./hooks/useAuthor";
export { useCreateAuthor } from "./hooks/useCreateAuthor";
export { useUpdateAuthor } from "./hooks/useUpdateAuthor";
export { useAuthorStatus } from "./hooks/useAuthorStatus";
export * from "./types/author.types";
